import { Achievement } from '@/types/Achievement';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-practice',
    name: 'Første skudd',
    description: 'Registrer din første treningsøkt',
    category: 'MILESTONE',
    rarity: 'COMMON',
    icon: 'Target',
    points: 10,
    requirements: { type: 'PRACTICE_COUNT', value: 1, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'practices-10',
    name: 'På god vei',
    description: 'Registrer 10 treningsøkter',
    category: 'MILESTONE',
    rarity: 'COMMON',
    tier: 'BRONZE',
    icon: 'Award',
    points: 25,
    requirements: { type: 'PRACTICE_COUNT', value: 10, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'practices-50',
    name: 'Dedikert skytter',
    description: 'Registrer 50 treningsøkter',
    category: 'MILESTONE',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Award',
    points: 75,
    requirements: { type: 'PRACTICE_COUNT', value: 50, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'practices-100',
    name: 'Århundrets skytter',
    description: 'Registrer 100 treningsøkter',
    category: 'MILESTONE',
    rarity: 'RARE',
    tier: 'GOLD',
    icon: 'Trophy',
    points: 150,
    requirements: { type: 'PRACTICE_COUNT', value: 100, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'practices-500',
    name: 'Mester',
    description: 'Registrer 500 treningsøkter',
    category: 'MILESTONE',
    rarity: 'EPIC',
    tier: 'PLATINUM',
    icon: 'Crown',
    points: 500,
    requirements: { type: 'PRACTICE_COUNT', value: 500, comparator: 'GREATER_OR_EQUAL' },
  },

  {
    id: 'streak-3',
    name: 'I gang',
    description: 'Tren 3 dager på rad',
    category: 'STREAK',
    rarity: 'COMMON',
    tier: 'BRONZE',
    icon: 'Flame',
    points: 15,
    requirements: { type: 'STREAK_DAYS', value: 3, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'streak-7',
    name: 'Uke-kriger',
    description: 'Tren 5 dager i løpet av en uke',
    category: 'STREAK',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Flame',
    points: 35,
    requirements: { type: 'PRACTICE_COUNT', value: 5, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'streak-30',
    name: 'Månedens mester',
    description: 'Tren 15 dager i løpet av en måned',
    category: 'STREAK',
    rarity: 'RARE',
    tier: 'GOLD',
    icon: 'Zap',
    points: 150,
    requirements: { type: 'PRACTICE_COUNT', value: 15, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'streak-100',
    name: 'Ustoppelig',
    description: 'Tren 50 dager i løpet av en sesong (3 måneder)',
    category: 'STREAK',
    rarity: 'LEGENDARY',
    tier: 'DIAMOND',
    icon: 'Star',
    points: 500,
    requirements: { type: 'PRACTICE_COUNT', value: 50, comparator: 'GREATER_OR_EQUAL' },
  },

  {
    id: 'arrows-1000',
    name: 'Tusen skudd',
    description: 'Skyt 1000 piler totalt',
    category: 'DEDICATION',
    rarity: 'COMMON',
    tier: 'BRONZE',
    icon: 'ArrowRight',
    points: 30,
    requirements: { type: 'ARROW_COUNT', value: 1000, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'arrows-5000',
    name: 'Pil-veteran',
    description: 'Skyt 5000 piler totalt',
    category: 'DEDICATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'ArrowRight',
    points: 100,
    requirements: { type: 'ARROW_COUNT', value: 5000, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'arrows-10000',
    name: 'Ti tusen piler',
    description: 'Skyt 10,000 piler totalt',
    category: 'DEDICATION',
    rarity: 'RARE',
    tier: 'GOLD',
    icon: 'Crosshair',
    points: 250,
    requirements: { type: 'ARROW_COUNT', value: 10000, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'arrows-50000',
    name: 'Pil-legende',
    description: 'Skyt 50,000 piler totalt',
    category: 'DEDICATION',
    rarity: 'LEGENDARY',
    tier: 'DIAMOND',
    icon: 'Target',
    points: 1000,
    requirements: { type: 'ARROW_COUNT', value: 50000, comparator: 'GREATER_OR_EQUAL' },
  },

  {
    id: 'perfect-end',
    name: 'Perfekt!',
    description: 'Skyt en perfekt runde (alle 10-ere)',
    category: 'PERFORMANCE',
    rarity: 'RARE',
    tier: 'GOLD',
    icon: 'Award',
    points: 100,
    requirements: { type: 'PERFECT_END', value: true },
  },
  {
    id: 'big-session',
    name: 'Maraton-økt',
    description: 'Skyt 200+ piler i én treningsøkt',
    category: 'DEDICATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Activity',
    points: 40,
    requirements: { type: 'ARROWS_IN_SESSION', value: 200, comparator: 'GREATER_OR_EQUAL' },
  },

  {
    id: 'first-competition',
    name: 'Konkurransedebut',
    description: 'Delta i din første konkurranse',
    category: 'COMPETITION',
    rarity: 'COMMON',
    tier: 'BRONZE',
    icon: 'Trophy',
    points: 25,
    requirements: { type: 'COMPETITION_COUNT', value: 1, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'competitions-10',
    name: 'Konkurranseskytter',
    description: 'Delta i 10 konkurranser',
    category: 'COMPETITION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Medal',
    points: 75,
    requirements: { type: 'COMPETITION_COUNT', value: 10, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'competition-winner',
    name: 'Seierherre',
    description: 'Vinn en konkurranse',
    category: 'COMPETITION',
    rarity: 'EPIC',
    tier: 'GOLD',
    icon: 'Crown',
    points: 250,
    requirements: { type: 'COMPETITION_WIN', value: true },
  },

  {
    id: 'all-categories',
    name: 'Allsidig skytter',
    description: 'Tren i alle fire kategorier',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Compass',
    points: 60,
    requirements: { type: 'ALL_CATEGORIES', value: 4, comparator: 'EQUALS' },
  },
  {
    id: 'indoor-specialist',
    name: 'Innendørs-spesialist',
    description: 'Registrer 50 innendørs treningsøkter',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Home',
    points: 50,
    requirements: {
      type: 'CATEGORY_PRACTICE',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { category: 'SKIVE_INDOOR' },
    },
  },
  {
    id: 'outdoor-enthusiast',
    name: 'Friluftsskytter',
    description: 'Registrer 50 utendørs treningsøkter',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Trees',
    points: 50,
    requirements: {
      type: 'CATEGORY_PRACTICE',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { category: 'SKIVE_OUTDOOR' },
    },
  },
  {
    id: '3d-hunter',
    name: '3D jeger',
    description: 'Registrer 50 3D/jakt treningsøkter',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Footprints',
    points: 50,
    requirements: {
      type: 'CATEGORY_PRACTICE',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { category: 'JAKT_3D' },
    },
  },
  {
    id: 'field-archer',
    name: 'Feltmester',
    description: 'Registrer 50 felt treningsøkter',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Mountain',
    points: 50,
    requirements: {
      type: 'CATEGORY_PRACTICE',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { category: 'FELT' },
    },
  },

  {
    id: 'bow-diversity',
    name: 'Buemangfold',
    description: 'Tren med 2 forskjellige buetyper',
    category: 'EXPLORATION',
    rarity: 'COMMON',
    tier: 'BRONZE',
    icon: 'Target',
    points: 20,
    requirements: { type: 'BOW_TYPE_COUNT', value: 2, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'bow-collector',
    name: 'Bue-samler',
    description: 'Tren med 3 forskjellige buetyper',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Package',
    points: 50,
    requirements: { type: 'BOW_TYPE_COUNT', value: 3, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'master-of-all-bows',
    name: 'Mester av alle buer',
    description: 'Tren med alle buetyper (minst 5 forskjellige)',
    category: 'EXPLORATION',
    rarity: 'EPIC',
    tier: 'GOLD',
    icon: 'Crown',
    points: 150,
    requirements: { type: 'BOW_TYPE_COUNT', value: 5, comparator: 'GREATER_OR_EQUAL' },
  },
  {
    id: 'recurve-rider',
    name: 'Recurve-rytter',
    description: 'Tren 50 økter med recurvebue',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Crosshair',
    points: 60,
    requirements: {
      type: 'BOW_TYPE_PRACTICES',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'RECURVE' },
    },
  },
  {
    id: 'compound-commander',
    name: 'Compound-kommandør',
    description: 'Tren 50 økter med compoundbue',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Zap',
    points: 60,
    requirements: {
      type: 'BOW_TYPE_PRACTICES',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'COMPOUND' },
    },
  },
  {
    id: 'longbow-legend',
    name: 'Langbue-legende',
    description: 'Tren 50 økter med langbue',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Flame',
    points: 60,
    requirements: {
      type: 'BOW_TYPE_PRACTICES',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'LONGBOW' },
    },
  },
  {
    id: 'barebow-archer',
    name: 'Barebow-bueskytter',
    description: 'Tren 50 økter med barebow',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'Circle',
    points: 60,
    requirements: {
      type: 'BOW_TYPE_PRACTICES',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'BAREBOW' },
    },
  },
  {
    id: 'horsebow-hero',
    name: 'Hestebue-helt',
    description: 'Tren 50 økter med hestebue',
    category: 'EXPLORATION',
    rarity: 'RARE',
    tier: 'GOLD',
    icon: 'Wind',
    points: 75,
    requirements: {
      type: 'BOW_TYPE_PRACTICES',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'HORSEBOW' },
    },
  },
  {
    id: 'traditionalist',
    name: 'Tradisjonalist',
    description: 'Tren 50 økter med tradisjonell bue',
    category: 'EXPLORATION',
    rarity: 'UNCOMMON',
    tier: 'SILVER',
    icon: 'History',
    points: 60,
    requirements: {
      type: 'BOW_TYPE_PRACTICES',
      value: 50,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'TRADITIONAL' },
    },
  },
  {
    id: 'recurve-dedicated',
    name: 'Recurve-dedikert',
    description: 'Skyt 10,000 piler med recurvebue',
    category: 'DEDICATION',
    rarity: 'RARE',
    tier: 'GOLD',
    icon: 'Target',
    points: 200,
    requirements: {
      type: 'BOW_TYPE_ARROWS',
      value: 10000,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'RECURVE' },
    },
  },
  {
    id: 'compound-expert',
    name: 'Compound-ekspert',
    description: 'Skyt 10,000 piler med compoundbue',
    category: 'DEDICATION',
    rarity: 'RARE',
    tier: 'GOLD',
    icon: 'Crosshair',
    points: 200,
    requirements: {
      type: 'BOW_TYPE_ARROWS',
      value: 10000,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'COMPOUND' },
    },
  },
  {
    id: 'longbow-master',
    name: 'Langbue-mester',
    description: 'Skyt 5,000 piler med langbue',
    category: 'DEDICATION',
    rarity: 'EPIC',
    tier: 'PLATINUM',
    icon: 'Award',
    points: 300,
    requirements: {
      type: 'BOW_TYPE_ARROWS',
      value: 5000,
      comparator: 'GREATER_OR_EQUAL',
      metadata: { bowType: 'LONGBOW' },
    },
  },

  {
    id: 'weather-warrior',
    name: 'Været stopper meg ikke',
    description: 'Tren i regn eller vind',
    category: 'SPECIAL',
    rarity: 'UNCOMMON',
    icon: 'CloudRain',
    points: 30,
    requirements: {
      type: 'WEATHER_CONDITION',
      value: true,
      metadata: { conditions: ['RAIN', 'WIND'] },
    },
  },
  {
    id: 'early-bird',
    name: 'Morgenfugl',
    description: 'Tren før kl. 07:00',
    category: 'SPECIAL',
    rarity: 'RARE',
    icon: 'Sunrise',
    points: 40,
    requirements: { type: 'EARLY_BIRD', value: 7, comparator: 'LESS_THAN' },
  },
  {
    id: 'night-owl',
    name: 'Natteugle',
    description: 'Tren etter kl. 22:00',
    category: 'SPECIAL',
    rarity: 'RARE',
    icon: 'Moon',
    points: 40,
    requirements: { type: 'NIGHT_OWL', value: 22, comparator: 'GREATER_OR_EQUAL' },
  },
];
