/**
 * All registered archery clubs in Norway.
 * Source: Norges Bueskytterforbund club registry.
 * Sorted alphabetically (nb-NO). Value = club name (stored as-is in the DB).
 */
export const NORWEGIAN_ARCHERY_CLUBS = [
	{ value: 'Akkerhaugen Bueskytterklubb', label: 'Akkerhaugen Bueskytterklubb' },
	{ value: 'Alta Sportsskytterklubb', label: 'Alta Sportsskytterklubb' },
	{ value: 'Altafjord Sportsskytterlag', label: 'Altafjord Sportsskytterlag' },
	{ value: 'Askim Bueskytterklubb', label: 'Askim Bueskytterklubb' },
	{ value: 'Aurskog-Høland Bueskyttere', label: 'Aurskog-Høland Bueskyttere' },
	{ value: 'Balsfjord Bueskytterklubb', label: 'Balsfjord Bueskytterklubb' },
	{ value: 'Bergen Bueskyttere', label: 'Bergen Bueskyttere' },
	{ value: 'Bodø Bueskytterforening', label: 'Bodø Bueskytterforening' },
	{ value: 'Breivoll Bueskytterklubb', label: 'Breivoll Bueskytterklubb' },
	{ value: 'Bærum og Omegn Bueskyttere', label: 'Bærum og Omegn Bueskyttere' },
	{ value: 'Bømlo Bueskytterklubb', label: 'Bømlo Bueskytterklubb' },
	{ value: 'Drammen Bueskyttere', label: 'Drammen Bueskyttere' },
	{ value: 'Eidskog Bueskytterklubb', label: 'Eidskog Bueskytterklubb' },
	{ value: 'Eidsvoll Bueskyttere', label: 'Eidsvoll Bueskyttere' },
	{ value: 'Elva/ Namsskogan IL - Bueskyttergruppa', label: 'Elva/ Namsskogan IL - Bueskyttergruppa' },
	{ value: 'Elverum Bueskyttere', label: 'Elverum Bueskyttere' },
	{ value: 'Fana Bueskytterklubb', label: 'Fana Bueskytterklubb' },
	{ value: 'Farsund og Lista Idrettsklubb - Bueskyttere', label: 'Farsund og Lista Idrettsklubb - Bueskyttere' },
	{ value: 'Fauske Bueklubb', label: 'Fauske Bueklubb' },
	{ value: 'Fjordane Bogeskytarlag', label: 'Fjordane Bogeskytarlag' },
	{ value: 'Flaktveit IK - Bueskyttergruppe', label: 'Flaktveit IK - Bueskyttergruppe' },
	{ value: 'Fredrikstad Bueskyttere', label: 'Fredrikstad Bueskyttere' },
	{ value: 'Fredrikstad Helsesportslag', label: 'Fredrikstad Helsesportslag' },
	{ value: 'Frøya IL Bueskyttergruppe', label: 'Frøya IL Bueskyttergruppe' },
	{ value: 'Førde Bogeskyttarklubb', label: 'Førde Bogeskyttarklubb' },
	{ value: 'Geitastrand IL - Bueskyttere', label: 'Geitastrand IL - Bueskyttere' },
	{ value: 'Gjerdrum & Omegn Helsesportlag', label: 'Gjerdrum & Omegn Helsesportlag' },
	{ value: 'Gjesdalbuane', label: 'Gjesdalbuane' },
	{ value: 'Grenland Bueskyttere', label: 'Grenland Bueskyttere' },
	{ value: 'H.E.G. IL - Bueskyttergruppe', label: 'H.E.G. IL - Bueskyttergruppe' },
	{ value: 'Hamar og Omegn Bueskyttere', label: 'Hamar og Omegn Bueskyttere' },
	{ value: 'Hammerfest Bueskytterlag', label: 'Hammerfest Bueskytterlag' },
	{ value: 'Hardanger Bogeskyttarklubb', label: 'Hardanger Bogeskyttarklubb' },
	{ value: 'Harstad Bueskyttere', label: 'Harstad Bueskyttere' },
	{ value: 'Harøy Bogeskytarlag', label: 'Harøy Bogeskytarlag' },
	{ value: 'Haugaland Bueskytterklubb', label: 'Haugaland Bueskytterklubb' },
	{ value: 'Havørn/Senjahopen UIL', label: 'Havørn/Senjahopen UIL' },
	{ value: 'Hisøy IL Bueskyttere', label: 'Hisøy IL Bueskyttere' },
	{ value: 'Hitra IL Bueskyttere', label: 'Hitra IL Bueskyttere' },
	{ value: 'Horten Bueskyttere', label: 'Horten Bueskyttere' },
	{ value: 'Hundeidvik IL - Bueskyttergruppe', label: 'Hundeidvik IL - Bueskyttergruppe' },
	{ value: 'Hurum SSK - Bueskyttergruppe', label: 'Hurum SSK - Bueskyttergruppe' },
	{ value: 'Hvaler IL - Bueskyttere', label: 'Hvaler IL - Bueskyttere' },
	{ value: 'Hvalstad IL - Bueskyttergruppe', label: 'Hvalstad IL - Bueskyttergruppe' },
	{ value: 'Hyllestad IL - Bueskyttergruppe', label: 'Hyllestad IL - Bueskyttergruppe' },
	{ value: 'Hønefoss Bueskytterklubb', label: 'Hønefoss Bueskytterklubb' },
	{ value: 'IF Fløya - Bueskyttergruppe', label: 'IF Fløya - Bueskyttergruppe' },
	{ value: 'IL Goma - Bueskyting', label: 'IL Goma - Bueskyting' },
	{ value: 'IL Skrim - Bueskyttere', label: 'IL Skrim - Bueskyttere' },
	{ value: 'Innherred Bueskytterklubb', label: 'Innherred Bueskytterklubb' },
	{ value: 'Kautokeino Pistolklubb, Bueskyttergruppe', label: 'Kautokeino Pistolklubb, Bueskyttergruppe' },
	{ value: 'Klepp Bueskyttere', label: 'Klepp Bueskyttere' },
	{ value: 'Kodal Bueskyttere', label: 'Kodal Bueskyttere' },
	{ value: 'Kongsvinger Bueskytterklubb', label: 'Kongsvinger Bueskytterklubb' },
	{ value: 'Kristiansand Bueskyttere', label: 'Kristiansand Bueskyttere' },
	{ value: 'Kvam Bogeskyttarklubb', label: 'Kvam Bogeskyttarklubb' },
	{ value: 'Kvinnherad Bogeskyttarklubb', label: 'Kvinnherad Bogeskyttarklubb' },
	{ value: 'Land Bueskytterklubb', label: 'Land Bueskytterklubb' },
	{ value: 'Larvik Bueskyttere', label: 'Larvik Bueskyttere' },
	{ value: 'Laugen Bueskytterklubb', label: 'Laugen Bueskytterklubb' },
	{ value: 'Leka IL Bueskyttere', label: 'Leka IL Bueskyttere' },
	{ value: 'Lillehammer Bueskytterklubb', label: 'Lillehammer Bueskytterklubb' },
	{ value: 'Lillestrøm & Omegn Bueskyttere', label: 'Lillestrøm & Omegn Bueskyttere' },
	{ value: 'Loen IL - Bogeskyttergruppa', label: 'Loen IL - Bogeskyttergruppa' },
	{ value: 'Lyngdal Bueskyttere', label: 'Lyngdal Bueskyttere' },
	{ value: 'Molde Bueskyttere', label: 'Molde Bueskyttere' },
	{ value: 'Moss Bueskyttere', label: 'Moss Bueskyttere' },
	{ value: 'Norges Bueskytterforbund', label: 'Norges Bueskytterforbund' },
	{ value: 'Oslo Bueskyttere', label: 'Oslo Bueskyttere' },
	{ value: 'Rana Bueskytterklubb', label: 'Rana Bueskytterklubb' },
	{ value: 'Rauma Bueskytterklubb', label: 'Rauma Bueskytterklubb' },
	{ value: 'Roan Pistolklubb - Bueskyttergruppe', label: 'Roan Pistolklubb - Bueskyttergruppe' },
	{ value: 'Romerike Bueskytterklubb', label: 'Romerike Bueskytterklubb' },
	{ value: 'Sandefjord Bueskyttere', label: 'Sandefjord Bueskyttere' },
	{ value: 'Sarpsborg Bueskyttere', label: 'Sarpsborg Bueskyttere' },
	{ value: 'Senja Bueskytterklubb', label: 'Senja Bueskytterklubb' },
	{ value: 'Skånland og Omegn IF - Bueskyttergruppe', label: 'Skånland og Omegn IF - Bueskyttergruppe' },
	{ value: 'Skreia IL - Bueskyttere', label: 'Skreia IL - Bueskyttere' },
	{ value: 'Skudeneshavn Bueskytterklubb', label: 'Skudeneshavn Bueskytterklubb' },
	{ value: 'Solør Bueskyttere', label: 'Solør Bueskyttere' },
	{ value: 'Sortland Bueskytterklubb', label: 'Sortland Bueskytterklubb' },
	{ value: 'Sportsklubben Vidar - Bueskyttergr.', label: 'Sportsklubben Vidar - Bueskyttergr.' },
	{ value: 'Stavanger Bueskyttere', label: 'Stavanger Bueskyttere' },
	{ value: 'Steig IL - Bueskyttergruppe', label: 'Steig IL - Bueskyttergruppe' },
	{ value: 'Stoksund SK - Bueskyttergr.', label: 'Stoksund SK - Bueskyttergr.' },
	{ value: 'Stord Bueskyttere', label: 'Stord Bueskyttere' },
	{ value: 'Strengereid IL - Bueskyttergruppe', label: 'Strengereid IL - Bueskyttergruppe' },
	{ value: 'Surnadal IL - Bueskyttergruppe', label: 'Surnadal IL - Bueskyttergruppe' },
	{ value: 'Svalbard Turn - Bueskyttergruppe', label: 'Svalbard Turn - Bueskyttergruppe' },
	{ value: 'Svelgen Turn & IF - Bogeskyttargruppe', label: 'Svelgen Turn & IF - Bogeskyttargruppe' },
	{ value: 'Sverresborg Bueskyttere', label: 'Sverresborg Bueskyttere' },
	{ value: 'Søndre Torsken Idrettslag, Bueskyttergruppe', label: 'Søndre Torsken Idrettslag, Bueskyttergruppe' },
	{ value: 'Sørfold Bueklubb', label: 'Sørfold Bueklubb' },
	{ value: 'Sørumsand IF - Bueskyttergruppe', label: 'Sørumsand IF - Bueskyttergruppe' },
	{ value: 'Tambarskjelvar IL - Bogeskyttargruppe', label: 'Tambarskjelvar IL - Bogeskyttargruppe' },
	{ value: 'Tinden Bueskytterklubb', label: 'Tinden Bueskytterklubb' },
	{ value: 'Tustna IL - Bueskyttergruppe', label: 'Tustna IL - Bueskyttergruppe' },
	{ value: 'Tønsberg & Omegn Bueskyttere', label: 'Tønsberg & Omegn Bueskyttere' },
	{ value: 'Ullensaker Bueskytterklubb', label: 'Ullensaker Bueskytterklubb' },
	{ value: 'Ulvungen IL - Bueskyttergruppe', label: 'Ulvungen IL - Bueskyttergruppe' },
	{ value: 'Valnesfjord IL - Bueskyttergruppe', label: 'Valnesfjord IL - Bueskyttergruppe' },
	{ value: 'Vestnes Bueskyttere', label: 'Vestnes Bueskyttere' },
	{ value: 'Vigra IL - Bueskyttere', label: 'Vigra IL - Bueskyttere' },
	{ value: 'Vinje Bogeskytterlag', label: 'Vinje Bogeskytterlag' },
	{ value: 'Vollan IK - Bueskyttergruppe', label: 'Vollan IK - Bueskyttergruppe' },
	{ value: 'Yrjar IL - Bueskyttergruppa', label: 'Yrjar IL - Bueskyttergruppa' },
	{ value: 'Ørje IL - Bueskyttergruppe', label: 'Ørje IL - Bueskyttergruppe' },
	{ value: 'Ørnes IL - Bueskyttergruppa', label: 'Ørnes IL - Bueskyttergruppa' },
	{ value: 'Ålesund Bueskytterklubb', label: 'Ålesund Bueskytterklubb' },
	{ value: 'Ås Bueskyttere', label: 'Ås Bueskyttere' },
] as const;

export type NorwegianArcheryClub = (typeof NORWEGIAN_ARCHERY_CLUBS)[number]['value'];

