import { StyleSheet } from 'react-native';
import { colors } from '@/styles/colors';

export const styles = StyleSheet.create({
  container: {
    gap: 14,
  },
  header: {
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
    marginTop: 10,
    color: colors.primary,
  },
  sub: {
    fontSize: 19,
    fontWeight: '600',
    textAlign: 'center',
    marginHorizontal: 12,
    color: colors.dark_primary,
    lineHeight: 24,
  },
  box: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 16,
  },
  featureItem: {
    width: '100%',
  },
  feather: {
    color: colors.white,
    fontSize: 32,
    alignSelf: 'center',
  },
  text: {
    color: colors.white,
    textAlign: 'center',
    fontSize: 19,
    fontWeight: '600',
    marginBottom: 10,
  },
  linksCard: {
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    alignItems: 'center',
  },
  linksTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 6,
  },
  link: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  webInfoBox: {
    marginTop: 12,
    width: '100%',
    backgroundColor: colors.tertiary,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.secondary,
  },
  webInfoTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 4,
    textAlign: 'center',
  },
  webInfoText: {
    fontSize: 14,
    color: colors.dark_primary,
    textAlign: 'center',
    lineHeight: 20,
  },
  sponsorCard: {
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    alignItems: 'center',
  },
  sponsor: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.secondary,
    textAlign: 'center',
    marginBottom: 8,
  },
  logo: {
    height: 120,
    width: 120,
  },
  sponsorLogo: {
    height: 80,
    width: 250,
  },
});
